import { createElement } from '@lwc/engine-dom';
import BasicFirstComponent from 'c/BasicFirstComponent';//Here c is default namespace.

describe('c-basic-first-component', () => {
    let element;
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    beforeEach(()=>{
      // Arrange
        element = createElement('c-basic-first-component', {
            is: BasicFirstComponent
        });

        // Act
        document.body.appendChild(element);
    })

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Assert
        const data = element.shadowRoot.querySelector('p');
        expect(data.textContent).toBe('Hellooo Basicsss');
    });


    it('Second Test case',()=>{
        let a=1+99;
        expect(a).toBe(100);
    })

});


//Explaination
// Yeh ek Jest Test Class hai jo aapke LWC component ki functionality verify karne ke liye use hoti hai. Isse hum bina browser khole check kar sakte hain ki component sahi kaam kar raha hai ya nahi.

// Aaiye iske har hisse aur syntax ko samajhte hain:

// 1. Imports (Zaroori Files)
// createElement: Yeh ek utility hai jo dummy browser environment (JSDOM) mein aapka component create karti hai.

// BasicFirstComponent: Yeh aapka actual component hai jise aap test kar rahe hain.

// describe: Yeh ek container hai jo related tests ko group karta hai. Isme aap component ka naam likhte hain.

// 2. Lifecycle Hooks (afterEach & beforeEach)
// afterEach(() => { ... }):

// Syntax: Yeh har ek test case (it block) ke khatam hone ke baad chalta hai.

// Kaam: Yeh purane test ke bache-khuche DOM elements ko saaf (cleanup) karta hai taaki agla test ek fresh page se shuru ho sake.

// beforeEach(() => { ... }):

// Syntax: Yeh har ek test case ke shuru hone se pehle chalta hai.

// Kaam (Arrange & Act):

// createElement: Component ka ek instance banata hai.

// appendChild: Us component ko virtual browser (document body) mein daalta hai taaki hum use test kar sakein.

// 3. The Test Cases (it blocks)
// Har ek it block ek specific "Sawal" ya "Check" hota hai.

// Test 1: UI Data Check
// JavaScript
// it('TODO: ...', () => {
//     const data = element.shadowRoot.querySelector('p');
//     expect(data.textContent).toBe('Hellooo Basicsss');
// });
// shadowRoot.querySelector('p'): Yeh component ke andar ja kar <p> tag ko dhundhta hai.

// expect(...).toBe(...): Yeh actual checking hai. Agar <p> ke andar "Hellooo Basicsss" nahi likha hoga, toh test fail ho jayega.

// Test 2: Simple Logic Check
// JavaScript
// it('Second Test case',()=>{
//     let a=1+99;
//     expect(a).toBe(100);
// })
// Kaam: Yeh sirf yeh check kar raha hai ki Jest ka math engine sahi chal raha hai. Agar a ki value 100 hai, toh test pass hai.

// Summary Table (Quick Revision)
// Syntax	Matlab / Kab chalta hai?
// describe	Poore test suite ka heading/group.
// beforeEach	Setup ke liye (Har test se pehle).
// afterEach	Safai ke liye (Har test ke baad).
// it	Ek single test case.
// expect	Humari umeed (kya result aana chahiye).
// shadowRoot	LWC ke internal HTML elements tak pahunchne ke liye.
// Kaam Karne ka Tarika (Workflow):
// Arrange: Component banao (beforeEach).

// Act: Zarurat pade toh button click ya input change karo (aapke case mein sirf render ho raha hai).

// Assert: Check karo ki result sahi hai ya nahi (expect).


// describe kya h and it kyya h funxtion ya kya

// Gemini said
// Simple bhasha mein kahein toh, describe aur it dono hi Jest (Testing Framework) ke functions hain. Inka use code ko organize karne aur test cases likhne ke liye kiya jata hai.

// Inhe aap ek Kitab (Book) ki tarah samajh sakte hain:

// describe: Kitab ka Chapter (Topic ka naam).

// it: Us chapter ke andar ka ek Paragraph (Specific test case).

// 1. describe Kya Hai?
// Yeh ek function hai jo Test Suite banane ke kaam aata hai. Iska kaam sirf related tests ko ek group mein rakhna hai.

// Syntax: describe('Description String', () => { ... })

// Kaam: Yeh batata hai ki hum kis cheez ko test kar rahe hain (Jaise: "Login Page" ya "Calculator Component").

// Zaroori kyun hai? Agar aapke paas 50 tests hain, toh describe se pata chalta hai ki kaunse 10 tests Component A ke hain aur kaunse Component B ke.

// 2. it Kya Hai?
// Yeh woh function hai jisme Actual Test Logic likha jata hai. Ise Test Case kehte hain.

// Syntax: it('Should do something', () => { ... })

// Kaam: Yeh ek specific feature ya function ko check karta hai.

// Naam ka matlab: Iska naam "it" isliye rakha gaya hai taaki padhne mein English sentence jaisa lage.

// English mein: "it should display the heading"

// Code mein: it('should display the heading', () => { ... })

// Dono ke beech ka difference (Table)
// Feature	describe	it
// Type	Suite (Group)	Test Case (Individual)
// Purpose	Related tests ko ek saath bundle karna.	Ek single logic ya UI element ko check karna.
// Nesting	Ek describe ke andar dusra describe ho sakta hai.	it ke andar dusra it nahi likha jata.
// Execution	Iske andar setup code (beforeEach) ho sakta hai.	Iske andar sirf assertions (expect) hote hain.
// Udaharan (Example):
// Agar hum ek Calculator test kar rahe hain:

// JavaScript
// describe('Calculator Testing', () => { // <--- Poora group

//     it('should add two numbers correctly', () => { // <--- Test 1
//         expect(1 + 2).toBe(3);
//     });

//     it('should subtract two numbers correctly', () => { // <--- Test 2
//         expect(5 - 2).toBe(3);
//     });

// });
// Summary: * describe = "Main kya test kar raha hoon?"
// it = "Kya yeh specific kaam sahi se ho raha hai?"